### ISSUE TITLE
Feature Request: Preserve Code Indentation When Copying from PDF

### ISSUE THREAD

**Issue by rakhmanov-tr** [facundobatista/jupynotex#14]
Hello,
First of all, thank you for this excellent repository. It works great and has been very helpful.

I have a feature request that I believe would enhance the usability of the generated PDF documents. Currently, when copying code snippets from the PDF, the indentation (tabulation) is lost. This makes it challenging to paste the code into various files while maintaining its structure.

Is there a way to preserve the code indentation when copying from the PDF? This would be particularly useful for those who want to reuse the code examples directly from the document.

I've found a partial solution using the Verbatim environment:

```
\begin{Verbatim}[tabsize=4,obeytabs=true,showspaces=true]
\end{Verbatim}
```

While this preserves indentation when copying, it unfortunately displays space symbols in the PDF, making the code less readable.

I understand this might be a complex feature to implement, but it would significantly improve the experience of working with code examples from the generated PDFs.

Thank you for considering this request. I appreciate your work and any insights you can provide on this matter.

Best regards,
Timur

**Comment by facundobatista** [comment]
Hello! 

Thanks for taking the time to propose a new functionality or fix!

Let me see if I understand correctly:

1. you have a jupyter notebook with, let's say, one cell. That cell has a Python code in the input that has some indentation... for example a for loop

2. that cell also has an output, which is not important for this issue

3. you build a PDF using latex and jupynotex, get some text and the cell with both input and output in your final PDF

4. you open a PDF with a viewer, select the code from the "input part" of the cell and paste it somewhere else, let's say a code editor

5. in the code editor the pasted text is the code *without* indentation?

Thanks!!

**Comment by rakhmanov-tr** [comment]
> Hello!
> 
> Thanks for taking the time to propose a new functionality or fix!
> 
> Let me see if I understand correctly:
> 
> 1. you have a jupyter notebook with, let's say, one cell. That cell has a Python code in the input that has some indentation... for example a for loop
> 2. that cell also has an output, which is not important for this issue
> 3. you build a PDF using latex and jupynotex, get some text and the cell with both input and output in your final PDF
> 4. you open a PDF with a viewer, select the code from the "input part" of the cell and paste it somewhere else, let's say a code editor
> 5. in the code editor the pasted text is the code _without_ indentation?
> 
> Thanks!!

Yes, you understood me correctly.

**Comment by rakhmanov-tr** [comment]
I found a working solution by using the `listings` package, click [here](https://tex.stackexchange.com/questions/19949/how-to-make-listings-code-indentation-remain-unchanged-when-copied-from-pdf).

```
\documentclass[12pt,oneside]{memoir}

\usepackage{listings}
\usepackage[T1]{fontenc}
\usepackage{xcolor}
\usepackage{textcomp}

\definecolor{codebg}{HTML}{EEEEEE}
\definecolor{codeframe}{HTML}{CCCCCC}

\lstset{language=Awk}
\lstset{backgroundcolor=\color{codebg}}
\lstset{frame=single}
\lstset{framesep=10pt}
\lstset{rulecolor=\color{codeframe}}
\lstset{upquote=true}
\lstset{basicstyle=\ttfamily}
\lstset{showstringspaces=false}

\begin{document}

This code example prints out all users on your system:

\begin{lstlisting}[language=c]
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define MAX_LINE_LEN 1024

int main() {
    char line[MAX_LINE_LEN];
    FILE *in = fopen("/etc/passwd", "r");
    if (!in) exit(EXIT_FAILURE);

    while (fgets(line, MAX_LINE_LEN, in) != NULL) {
        char *sep = strchr(line, ':');
        if (!sep) exit(EXIT_FAILURE);
        *sep = '\0';
        printf("%s\n", line);
    }
    fclose(in);
    return EXIT_SUCCESS;
}
\end{lstlisting}

\end{document}
```
